# Generated by Django 4.2.27 on 2025-12-23 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(default=datetime.date.today, help_text='Data em que o livro foi devolvido.', verbose_name='Data Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(verbose_name='Previsão devolução'),
        ),
    ]
