# Generated by Django 4.2.27 on 2026-01-16 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('editoras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('edicao', models.CharField(max_length=2)),
                ('ano_publicacao', models.DateField()),
                ('isbn', models.CharField(max_length=14)),
                ('numero_paginas', models.IntegerField()),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas', verbose_name='Capa')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor', verbose_name='Autor')),
                ('editora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoras.editora', verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Livro',
                'ordering': ['titulo'],
            },
        ),
    ]
